### PR TITLE
Update about.lua

### PR DESCRIPTION
**Pull request by shahabsaf1**

### CODE REVIEW

**Comment by Mrhalix** [comment]
kar mikone?

**Comment by shahabsaf1** [comment]
Yes

**Comment by IDeactive** [comment]
ok khodam test mikonm age shod mizaram :+1:

**Comment by Mrhalix** [comment]
sorry kar nakard 😄

**Comment by shahabsaf1** [comment]
Cuze launch edit she

**Comment by IDeactive** [comment]
han ? :)

**Pull request closed without merging**
